// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaO5k38lCuS5qKiAFARTXjdWj7gOn1g68',
    appId: '1:1071869909520:web:294ec524db8de4e11ec895',
    messagingSenderId: '1071869909520',
    projectId: 'chatfeature-c1d03',
    authDomain: 'chatfeature-c1d03.firebaseapp.com',
    storageBucket: 'chatfeature-c1d03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8AuxU1XpAz2UhVHdjhsP0mGNhd03Y3hY',
    appId: '1:1071869909520:android:235f84ae11ad123a1ec895',
    messagingSenderId: '1071869909520',
    projectId: 'chatfeature-c1d03',
    storageBucket: 'chatfeature-c1d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKIx45AiEVA67NbeSr4QU3M2IaPXpSxI',
    appId: '1:1071869909520:ios:b1e86bec324b46411ec895',
    messagingSenderId: '1071869909520',
    projectId: 'chatfeature-c1d03',
    storageBucket: 'chatfeature-c1d03.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKIx45AiEVA67NbeSr4QU3M2IaPXpSxI',
    appId: '1:1071869909520:ios:3da9784ae5c786fa1ec895',
    messagingSenderId: '1071869909520',
    projectId: 'chatfeature-c1d03',
    storageBucket: 'chatfeature-c1d03.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
