// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDBvx053a45rCpxElHTc-ChOMCU-uR8I',
    appId: '1:387887694663:web:05dc6b52bb40b101d08262',
    messagingSenderId: '387887694663',
    projectId: 'uhm-social-software',
    authDomain: 'uhm-social-software.firebaseapp.com',
    storageBucket: 'uhm-social-software.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBceG-jgxKSsMeqS_09jnMSK9oejgK5RiI',
    appId: '1:387887694663:android:be4b53ad13f1e9b3d08262',
    messagingSenderId: '387887694663',
    projectId: 'uhm-social-software',
    storageBucket: 'uhm-social-software.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEfcfj3fLT5MpMPmWftJLj5km2I45c8R0',
    appId: '1:387887694663:ios:2a30a71163ea96a5d08262',
    messagingSenderId: '387887694663',
    projectId: 'uhm-social-software',
    storageBucket: 'uhm-social-software.appspot.com',
    iosClientId: '387887694663-e5itu1v2uon1kcblaq15tnkfafqhrkor.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEfcfj3fLT5MpMPmWftJLj5km2I45c8R0',
    appId: '1:387887694663:ios:3a42fa777fe9a0bdd08262',
    messagingSenderId: '387887694663',
    projectId: 'uhm-social-software',
    storageBucket: 'uhm-social-software.appspot.com',
    iosClientId: '387887694663-dgam1mk92grhkfkro0amaf86etgdsetk.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
